# Generated by Django 4.2.3 on 2023-07-20 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='comeleted',
            field=models.BooleanField(default=False),
        ),
    ]
