# Generated by Django 4.2.3 on 2023-07-20 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_alter_todo_label'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='comeleted',
            new_name='completed',
        ),
    ]
